# @package _group_

actions:
  vergence:
      - -1.125
      - -0.5625
      - -0.28125
      - -0.140625
      - 0.
      - 0.140625
      - 0.28125
      - 0.5625
      - 1.125
  cyclo:
    - 0.
n_actions:
  vergence: 9
  cyclo: 1
