# @package _group_

actions:
  tilt:
      - -2.25
      - -1.125
      - -0.5625
      - -0.28125
      - 0.
      - 0.28125
      - 0.5625
      - 1.125
      - 2.25
  pan:
      - -2.25
      - -1.125
      - -0.5625
      - -0.28125
      - 0.
      - 0.28125
      - 0.5625
      - 1.125
      - 2.25
n_actions:
  tilt: 9
  pan: 9
