# @package _group_


backend: tensorflow
class_name: Sequential
config:
  layers:
  - class_name: Conv2D
    config:
      activation: linear
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      data_format: channels_last
      dilation_rate:
      - 1
      - 1
      dtype: float32
      filters: ${decoder_out_size:${agent.pathways.pavro.encoder_model_arch.config.layers.0.config.kernel_size.0},${agent.pathways.pavro.encoder_model_arch.config.layers.0.config.kernel_size.1},6}
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config:
          seed: null
      kernel_regularizer: null
      kernel_size:
      - 1
      - 1
      name: conv2d_6
      padding: valid
      strides:
      - 1
      - 1
      trainable: true
      use_bias: true
  name: sequential_2
keras_version: 2.3.0-tf
