# @package _group_


n_scales: 3

description:
  fine:
    resolution: 32
    view_angle: 9
    downsampling: 3
  middle:
    resolution: 32
    view_angle: 18
    downsampling: 3
  coarse:
    resolution: 32
    view_angle: 27
    downsampling: 3
