

episode_length: 10
n_evaluation_batch: 1
batch_size: 64
updates_per_sample: 5
reward_scaling: 600

critic_learning_rate:
  -
    iteration: 0
    lr: 1e-3
  -
    iteration: 4000
    lr: 1e-4
  -
    iteration: 12000
    lr: 5e-5

encoder_learning_rate:
  -
    iteration: 0
    lr: 1e-3
  -
    iteration: 4000
    lr: 1e-4
  -
    iteration: 12000
    lr: 5e-5

test_conf_path: ${hydra:runtime.cwd}/../config/test_conf/default_at_2m.pkl
