# @package _group_

episode_length: 10
n_evaluation_batch: 20
batch_size: 64
updates_per_sample: 16
reward_scaling: 1500

critic_learning_rate:
  -
    iteration: 0
    lr: 8e-5

encoder_learning_rate:
  -
    iteration: 0
    lr: 1e-3

test_conf_path: ${hydra:runtime.cwd}/../config/test_conf/default_at_2m.pkl
